[package]
name = "sip-endian"
version = "0.1.0"
authors = ["Michael Woerister <michaelwoerister@posteo>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "sip-endian"
path = "main.rs"
